name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'bongo-cat-electron/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd bongo-cat-electron
        npm ci
        
    - name: Build Mac app
      run: |
        cd bongo-cat-electron
        npm run build:mac
        
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: bongo-cat-mac-dmg
        path: bongo-cat-electron/dist/*.dmg
        
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: bongo-cat-electron/dist/*.dmg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}